# -*- coding: utf-8 -*-
"""P1HW1_ArchieAmir.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lSLYkoMJk-3Dx1j9DY4wmT4pkS9k5eII
"""

#Amir Archie
#2/10/2025
#Introduction to Python 3
#Using Python's input and print functions



print("-----Calculating Exponents-----")
print()

base_value = int(input("Enter an integer as the base value:"))
Exponent_value = int(input("Enter an integer as the exponent:"))
print()
print(base_value, "Riased to the power of", Exponent_value, "is", base_value * Exponent_value)
print()

print("-----Adding and Subtraction-----")
starting_value = int(input("Enter starting integer:"))
Integer_add = int(input("Enter an integer to add:"))
Integer_subtract = int(input("Enter an integer to subtract:"))
print(starting_value,  "+", Integer_add , "-", Integer_subtract, "Is equal to", starting_value + Integer_add - Integer_subtract)

print()