# -*- coding: utf-8 -*-
"""P1HW2_ArchieAmir.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nC9e91tPnuVc68VKcSxDnsSt0Lp3Nu8U
"""

# Amir Archie
#2/11/25
#P1HW2
# Create a program that does some basic math on numbers that are entered.







print("This program calculates and displays travel expenses")
Enter_budget = int(input("Enter Budget: "))
Travel_destination = input("Enter your travel destination: ")
Gas_money = int(input("How much do you think you will spend on gas? "))
Accomodation_money = int(input("How much do you think you will spend on accomodation/hotel? "))
Food_money = int(input("last, how much do you think you will spend on food? "))
print()
print("------------Travel Expenses------------")
print("Location: ", Travel_destination)
print("Initial Budget: $", Enter_budget)
print()
print("Fuel: $", Gas_money)
print("Accomodation: $", Accomodation_money)
print("Food: $", Food_money)
print()
print("Remaining Balance: $", Enter_budget - Gas_money - Accomodation_money - Food_money)