# -*- coding: utf-8 -*-
"""P2LAB.ArchieAmir.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XaRFLCkp1bhvqxQt9gNY5yu6VSjUiEz7
"""

#Amir Archie
#2/19/25
#P2LAB
#Using dictionaries


cars_names= {'Camero':18.21, 'Prius':52.36, 'Model S':110, 'Silverado':26}
cars_keys = cars_names.keys()
print(cars_keys)
print(*cars_keys, sep = ", ")

car_name = input("Enter a car name: ")
car_mpg = cars_names[car_name]
print(f"The {car_name} gets {car_mpg} miles per gallon.")

miles_driven = float(input(f"How many miles will you drive the {car_name}? "))
gallons_needed = miles_driven/car_mpg
print(f"{gallons_needed} gallon(s) of gas are needed to drive the {car_name} {miles_driven} miles.")