# -*- coding: utf-8 -*-
"""P2LAB1ArchieAmir.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CkuXfhUEgdjAiSwV5aSuAs7COvYEglA5
"""

# Variables and Expressions
# Amir Archie
# 2/17/2025/
# P2LAB1
# Using the radius, which should be given by the user as a float, the program will calculate the diameter, circumference, and area of a circle.


Radius = float(input("What is the radius of circle "))
Diameter = Radius * 2
Circumference = 2 * 3.14 * Radius
Area = 3.14 * Radius * Radius
print("The diameter of the circle is ", Diameter)
print("The circumference of the circle is ", Circumference)
print("The area of the circle is ", Area)