# -*- coding: utf-8 -*-
"""P3HW2_ArchieAmir.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18jfOEfgsn-y-pUFxVgcndiIGUofydvSz
"""

#Amir Archie
#3/10/25
#P3WH2
#Assignment assess student understanding of decision structuion


employee_name = input("Enter employee's name:")
hours_worked = float(input("Enter number of hours worked:"))
hourly_pay_rate = float(input("Enter hourly pay rate:"))
print("------------------------------------------------------")
print("Employee Name:", employee_name)
print()
print("Hours Worked  Pay Rate  Overtime Overtime Pay RegHour Pay  Gross Pay")
print("----------------------------------------------------------------------------")
if hours_worked > 40:
  overtime_hours = hours_worked - 40
  overtime_pay = overtime_hours * (hourly_pay_rate * 1.5)
  reg_hour_pay = 40 * hourly_pay_rate
  gross_pay = reg_hour_pay + overtime_pay
  print(f"{hours_worked:10.2f}{hourly_pay_rate:10.2f}{overtime_hours:10.2f}{overtime_pay:10.2f}{reg_hour_pay:10.2f}{gross_pay:10.2f}")

else:
 overtime_hours = 0
 overtime_pay = 0
 reg_hour_pay = hours_worked * hourly_pay_rate
 gross_pay = reg_hour_pay
 print(f"{hours_worked:10.2f}{hourly_pay_rate:10.2f}{overtime_hours:10.2f}{overtime_pay:10.2f}{reg_hour_pay:10.2f}{gross_pay:10.2f}")