# -*- coding: utf-8 -*-
"""P3WH1.ArchieAmir.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1962_75bj5cLss8KTuwZqFqT7L7IkcTff
"""

#Amir Archie
#3/10/25
#P3WH1



# This program takes a number grade , determines average and displays letter grade for average.

# Enter grades for six modules

mod_1 = float(input('Enter grade for Module 1: '))
mod_2 = float(input('Enter grade for Module 2: '))
mod_3 = float(input('Enter grade for Module 3:' ))
mod_4 = float(input('Enter grade for Module 4: '))
mod_5 = float(input('Enter grade for Module 5: '))
mod_6 = float(input('Enter grade for Module 6: '))

# add grades entered to a list

grades = [mod_1, mod_2, mod_3, mod_4, mod_5, mod_6]
# TO DO: determine lowest, highest , sum and average for grades

# Convert grades to integers before calculating sum, min, and max
grades = [int(grade) for grade in grades] # This line converts the string elements of 'grades' to integers

low = min(grades)
high = max(grades) # corrected high function
sum_grades = sum(grades) # Use sum_grades instead of sum to avoid shadowing the built-in sum function
avg = sum_grades / len(grades) # added average calculation
print()
print(f"Average: {avg}")

# determine letter grade for average


if avg >= 90:
    print('Your grade is: A')
elif avg > 80: # corrected elif statement
    print('Your grade is: B')
elif avg >= 70: #added elif statement for C
    print('Your grade is:C') #added print statment
elif avg >= 60: #added elif for D
    print('Your grade is:D') #added print statement
else:
    print('Your grade is: F') # TO DO: finish this