# -*- coding: utf-8 -*-
"""p4hw1_Archieamir.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g9nj5Qbdh-acHyhse7QekfdA53n0-BVk
"""

Num_scores = int(input("How many scores do you want to enter? "))
scores = []
for i in range(Num_scores):
    score = float(input(f"Enter score #{i+1}: "))
    while score < 0 or score > 100:
        print("Invalid score entered !!!. Score should be between 0 and 100.")
        score = float(input(f"Enter score #{i+1}: "))
    scores.append(score)
print()
average_score = sum(scores) / len(scores)
if (80 <= average_score <= 100):
    letter_grade = 'A'
elif (65 <= average_score <= 79):
    letter_grade = 'B'
elif (50 <= average_score <= 64):
    letter_grade = 'C'
elif (35 <= average_score <= 49):
    letter_grade = 'D'
else:
    letter_grade = 'F'
print("-------------Results-------------")
lowest_score = min(scores)
scores.remove(lowest_score)
print(f"Lowest Score: {lowest_score}")
print(f"Modifiied list: {scores}")
print(f"Scores Average: {sum(scores)/len(scores)}")
print(f"Grade: {letter_grade}")