# -*- coding: utf-8 -*-
"""P4LAB_ArchieAmir.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GSDohXnJuTX_Gfejzd8YCO2ROg9o7bmM
"""

#Amir Archie
#3/24/25
#P4LAB2
#Using while loop and for loop togther

run_again = 'yes'
while run_again !="no":

    user_num = int(input("Enter an integer:"))
    if user_num >= 0:
        for item in range(1,13):
            print(f"{user_num}* {item}= {user_num * item}")
    else:
        print("This program does not handle negative values")

    run_again = input("Do you want to run again? ")

print("Program is ending.....")